site_name: Wiki movidas
site_author: vatojavi
nav:
  - Introduction: 'index.md'
  - Inform치tica:
    - Programaci칩n:
      - Python: 
        - General: informatica/python/general.md
        - Regresi칩n: informatica/python/regresion.md
        - Pandas: informatica/python/pandas.md
        - Plots: informatica/python/plots.md
        - Conexi칩n a DBs: informatica/python/cDB.md
      - Kotlin:
        - General: informatica/kotlin/kotlin.md
      - JavaScript:
        - General: informatica/js/js.md
      - Flutter: informatica/flutter/flutter.md
      
    - Linux: informatica/linux/linux.md
    - Bash: informatica/bash/bash.md
    - Docker: informatica/docker/docker.md
    - Bases de Datos:
      - PostgreSQL:  informatica/BBDD/Postgres.md
      - MySQL:  informatica/BBDD/MySQL.md
    - Editores:
      - VSCode:  informatica/editores/vscode.md
      - Jupyter: informatica/editores/jupyter.md

  
  - Recetas 游꺑游볫: 
    - Comidas:
      - Fajitas: a_zampar/comidas/fajitas.md
      - Arroz con pollo: a_zampar/comidas/arroz_pollo.md
      - Pollo agridulce: a_zampar/comidas/pollo_agridulce.md
      - Pasta Feta: a_zampar/comidas/pasta_feta.md
      - Pasta carbonara: a_zampar/comidas/pasta_carbonara.md
      - Arroz Pollo con brocoli y setas: a_zampar/comidas/arroz_pollo_brocoli_oriental.md
      - Ensalada Cesar: a_zampar/comidas/ensalada_cesar.md
      

theme:
  name: material
  palette:
    scheme: slate
    primary: pink
    accent: red

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

repo_name: vatojavier/wiki
repo_url: https://github.com/vatojavier/wiki
