site_name: Wiki movidas
site_author: vatojavi
nav:
  - Introduction: 'index.md'
  - Informática: 
    - Informática: informatica/informatica.md
    - Python: 
      - Bucles óptimos: informatica/python/bucles_optimos.md
      - Regresión: informatica/python/regresion.md
      - Pandas: informatica/python/pandas.md
      - Conexión a DBs: informatica/python/cDB.md
    - Bases de Datos:
      - PostgreSQL:  informatica/BBDD/Postgres.md
    - Editores:
      - VSCode:  informatica/editores/vscode.md
      - Jupyter: informatica/editores/jupyter.md
    - Control de versiones:
      - Git: informatica/control_versiones/git.md
  
  - Jamada: 
    - Comidas:
      - Fajitas: a_zampar/comidas/fajitas.md

theme:
  name: material
  palette:
    scheme: slate
    primary: pink
    accent: red

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite

repo_name: vatojavier/wiki
repo_url: https://github.com/vatojavier/wiki
